version: "3.8"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hotel
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
    - 5432
  app:
    container_name: hotel
    image: juxvile/firstimage
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hotel
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.profiles.active=postgres
    depends_on:
      - db
    ports:
    - 8082